name: goreleaser

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    env:
      TAG_VERSION: $(make app-version)
      TAG_EXIST: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v4
      - name: Tag New Version
        run: |
          if git show-ref --tags "refs/tags/${{ env.TAG_VERSION }}" >/dev/null 2>&1; then
            echo "Tag ${{ env.TAG_VERSION }} already exists"
            echo "TAG_EXIST=true" >> $GITHUB_ENV
          else
            git tag ${{ env.TAG_VERSION }}
            git push origin ${{ env.TAG_VERSION }}
          fi
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        if: ${{ env.TAG_EXIST != 'true' }}
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser
          # 'latest', 'nightly', or a semver
          version: '~> v1'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Your GoReleaser Pro key, if you are using the 'goreleaser-pro' distribution
          # GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
